site_name: 1D Burgers PINN GQM
site_author: Eduardo Furlan
site_url: https://efurlanm.github.io/421/
copyright: CC BY 4.0 License
repo_name: "421"
repo_url: http://github.com/efurlanm/421/
docs_dir: src
site_dir: docs
theme:
    name: material
    # squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    palette:
        primary: cyan
        accent: cyan
    font: false
    features:
        - header.autohide
plugins:
    - search
markdown_extensions:
    - def_list
    - md_in_html
    - tables
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
extra_css:
    - css/extra.css
    - https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css
extra_javascript:
    - javascripts/katex.js
    - https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js
    - https://cdn.jsdelivr.net/npm/katex/dist/contrib/auto-render.min.js
exclude_docs: |
    .*
nav:
    - Abstract: "index.md"
    - 1. Introduction: 'introduction.md'
    - 2. Material and methods: 'material.md'
    - 3. Results: 'results.md'
    - 4. Conclusions: 'conclusions.md'
    - References: 'references.md'
